version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Environment variables
          command: |
            echo 'export ENDPOINT_SENSORS="$ENDPOINT_SENSORS"' >> $BASH_ENV
            if [ "$CIRCLE_BRANCH" == "develop" ]; then
              echo 'export ENV_SUFFIX="$STAGING_ENV_SUFFIX"' >> $BASH_ENV
              echo 'export DATABASE_HOST="$STAGING_DATABASE_HOST"' >> $BASH_ENV
              echo 'export DATABASE_NAME="$STAGING_DATABASE_NAME"' >> $BASH_ENV
              echo 'export DATABASE_USER="$STAGING_DATABASE_USER"' >> $BASH_ENV
              echo 'export DATABASE_PASS="$STAGING_DATABASE_PASS"' >> $BASH_ENV
              echo 'export JWT_SECRET="$STAGING_JWT_SECRET"' >> $BASH_ENV
            fi
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              echo 'export ENV_SUFFIX="$PRODUCTION_ENV_SUFFIX"' >> $BASH_ENV
              echo 'export DATABASE_HOST="$PRODUCTION_DATABASE_HOST"' >> $BASH_ENV
              echo 'export DATABASE_NAME="$PRODUCTION_DATABASE_NAME"' >> $BASH_ENV
              echo 'export DATABASE_USER="$PRODUCTION_DATABASE_USER"' >> $BASH_ENV
              echo 'export DATABASE_PASS="$PRODUCTION_DATABASE_PASS"' >> $BASH_ENV
              echo 'export JWT_SECRET="$PRODUCTION_JWT_SECRET"' >> $BASH_ENV
            fi
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run:
          name: Dependencies
          command: make node_modules
      - save_cache:
          paths:
            - ./node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Linting
          command: make lint
      - run:
          name: Build
          command: make build
      - run:
          name: Push images
          command: |
            docker login $DOCKER_REGISTRY_HOST -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASS
            make push
      - run:
          name: Deploy
          command: make deploy
