version: '2.1'

services:
  node:
    image: docker.wouterdeschuyter.be/api.wouterdeschuyter.be/node:latest
    container_name: be.wouterdeschuyter.api
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=reverse-proxy'
      - 'traefik.http.middlewares.bewouterdeschuyterapi.redirectscheme.scheme=https'
      - 'traefik.http.routers.bewouterdeschuyterapi-http.entrypoints=web'
      - 'traefik.http.routers.bewouterdeschuyterapi-http.rule=Host(`api.wouterdeschuyter.be`)'
      - 'traefik.http.routers.bewouterdeschuyterapi-http.middlewares=bewouterdeschuyterapi'
      - 'traefik.http.routers.bewouterdeschuyterapi-https.entrypoints=websecure'
      - 'traefik.http.routers.bewouterdeschuyterapi-https.rule=Host(`api.wouterdeschuyter.be`)'
      - 'traefik.http.routers.bewouterdeschuyterapi-https.tls.certresolver=myhttpchallenge'
    restart: unless-stopped
    mem_limit: 128mb
    volumes:
      - ./data:/data
    networks:
      - reverse-proxy
      - mariadb

networks:
  reverse-proxy:
    external: true
  mariadb:
    external: true
