version: '2'

services:
  node:
    image: docker.wouterdeschuyter.be/api.wouterdeschuyter.be/node:latest-staging
    restart: unless-stopped
    mem_limit: 128mb
    volumes:
      - ./data:/data
    environment:
      - VIRTUAL_HOST=api-staging.wouterdeschuyter.be
      - VIRTUAL_PORT=3001
      - LETSENCRYPT_HOST=api-staging.wouterdeschuyter.be
      - LETSENCRYPT_EMAIL=wouter.de.schuyter@gmail.com
    networks:
      - default
      - webproxy
      - mariadb

networks:
  webproxy:
    external: true
  mariadb:
    external: true
