version: '2'

services:
  node:
    image: docker.wouterdeschuyter.be/api-wouterdeschuyter-staging-node
    restart: unless-stopped
    mem_limit: 64mb
    environment:
      - VIRTUAL_HOST=api-staging.wouterdeschuyter.be
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=api-staging.wouterdeschuyter.be
      - LETSENCRYPT_EMAIL=wouter.de.schuyter@gmail.com
    networks:
      - default
      - webproxy
      - mariadb
    logging:
      options:
        max-size: 2m
        max-file: '5'

networks:
  webproxy:
    external: true
  mariadb:
    external: true
