version: '2'

services:
  mariadb:
    image: mariadb:10.4
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker

  node:
    image: node:12-slim
    volumes:
      - ../:/code
    working_dir: /code
    command: bash -c "npm install --loglevel verbose && npm run sync:models && npm run dev"
    ports:
      - 3000:3000
    depends_on:
      - mariadb
